basePath: /
host: localhost:7577
info:
  contact: {}
  description: Реализация домашних заданий для курса
  title: ML integration course
  version: 0.0.2
paths:
  /calculate:
    post:
      consumes:
      - application/json
      parameters:
      - description: Объект с числами
        in: body
        name: numbers
        required: true
        schema:
          additionalProperties:
            type: integer
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: integer
            type: object
      summary: Вычисление суммы
  /query:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: CSV-файл
        in: formData
        name: file
        required: true
        type: file
      - description: SQL-запрос
        in: formData
        name: sql
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Выполнить SQL по CSV
swagger: "2.0"
