name: Build prod Docker image

on:
  push:
    branches:
      - master

jobs:
  docker-build:
    name: Build and push prod Docker image to GHCR
    runs-on: ubuntu-latest

    steps:
      - name: Load code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

  deploy:
    name: Deploy to dev
    needs: docker-build
    runs-on: ubuntu-latest

    steps:
      - name: Load code
        uses: actions/checkout@v4

      - name: Copy compose files
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "docker-compose.yml"
          target: /opt/ml_integration

      - name: Deploy with docker compose
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /opt/ml_integration
            echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker compose -f docker-compose.yml pull
            docker compose -f docker-compose.yml up -d
