name: Build dev Docker image

on:
  push:
    branches-ignore:
      - master

jobs:
  docker-build:
    name: Build and push Docker dev image to GHCR
    runs-on: ubuntu-latest

    steps:
      - name: Load code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}_dev:latest
